services:
  front:
    build: ./
    container_name: meal_recognizer
    ports:
      - "3200:3000"
    environment:
      NODE_ENV: production
    networks:
      - meal_recognizer
    restart: always

networks:
  meal_recognizer:
    driver: bridge